var enemyStats = [
    galyna = {
        name: "Galyna",
        baseCharacter: "galynaBattle",
        ch: "galynaCH",
        currentHP: 16,
        maxHP: 150,
        currentEN: 10,
        maxEN: 10,
        attack: 20,
        weapon: "default",
        weaponMult: 1,
        defence: 10,
        evasion: "5%",
        description: "He's the leader of the bunch",
        specDesc: "hits a lot"
    },
    arron = {
        name: "Arron",
        baseCharacter: "arronBattle",
        ch: "arronCH",
        currentHP: 200,
        maxHP: 200,
        currentEN: 10,
        maxEN: 10,
        attack: 15,
        weapon: "default",
        weaponMult: 1,
        defence: 10,
        evasion: "5%",
        description: "He's the leader of the bunch",
        specDesc: "hits a lot"
    },
    daemon = {
        name: "Daemon",
        baseCharacter: "daemonBattle",
        ch: "daemonCH",
        currentHP: 200,
        maxHP: 200,
        currentEN: 10,
        maxEN: 10,
        attack: 15,
        weapon: "default",
        weaponMult: 1,
        defence: 10,
        evasion: "5%",
        description: "He's the leader of the bunch",
        specDesc: "hits a lot"
    },
    henry = {
        name: "Henry",
        baseCharacter: "henryBattle",
        ch: "henryCH",
        currentHP: 200,
        maxHP: 200,
        currentEN: 10,
        maxEN: 10,
        attack: 15,
        weapon: "default",
        weaponMult: 1,
        defence: 10,
        evasion: "5%",
        description: "He's the leader of the bunch",
        specDesc: "hits a lot"
    },    
    ramin = {
        name: "Ramin",
        baseCharacter: "raminBattle",
        ch: "raminCH",
        currentHP: 200,
        maxHP: 200,
        currentEN: 10,
        maxEN: 10,
        attack: 15,
        weapon: "default",
        weaponMult: 1,
        defence: 10,
        evasion: "5%",
        description: "He's the leader of the bunch",
        specDesc: "hits a lot"
    },    
]